"use strict";

const { AISearchError, AISearchErrorCodes } = require("../diagnostics/aiSearchErrors.cjs");

const AIErrorCode = Object.freeze({
  MODEL_NOT_FOUND: "AI_SEARCH_MODEL_NOT_FOUND",
  MODEL_NOT_INSTALLED: "AI_SEARCH_MODEL_NOT_INSTALLED",
  MODEL_INTEGRITY_FAILED: "AI_SEARCH_MODEL_INTEGRITY_FAILED",
  MODEL_INCOMPATIBLE: "AI_SEARCH_MODEL_INCOMPATIBLE",
  RUNTIME_NOT_FOUND: "AI_SEARCH_RUNTIME_NOT_FOUND",
  RUNTIME_UNAVAILABLE: "AI_SEARCH_RUNTIME_UNAVAILABLE",
  RUNTIME_LOAD_FAILED: "AI_SEARCH_RUNTIME_LOAD_FAILED",
  INFERENCE_FAILED: "AI_SEARCH_INFERENCE_FAILED",
  TASK_UNSUPPORTED: "AI_SEARCH_TASK_UNSUPPORTED",
  CAPABILITY_UNAVAILABLE: "AI_SEARCH_CAPABILITY_UNAVAILABLE",
  LICENSE_METADATA_MISSING: "AI_SEARCH_LICENSE_METADATA_MISSING",
  RESOURCE_BUSY: "AI_SEARCH_RESOURCE_BUSY",
});

class AIError extends AISearchError {
  constructor(code, message, details = null) {
    super(code || AISearchErrorCodes.AI_SEARCH_MODEL_FAILED, message, details);
    this.name = "AIError";
  }
}

module.exports = {
  AIErrorCode,
  AIError,
};
